In [1]:
import pandas as pd

In [2]:
#reading the excel file
df = pd.read_excel('kenyagazettedregisterperpollingstation2017.xlsx')

In [3]:
#displaying data from excel file 
df

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW CODE,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
0,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,BOMU PRIMARY SCHOOL,9625.0,1.001000e+12,BOMU PRIMARY SCHOOL,687
1,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
2,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
3,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
4,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
...,...,...,...,...,...,...,...,...,...,...,...,...
40879,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,112.0,KAMITI MEDIUM PRISON,160.0,4.929215e+13,KAMITI MEDIUM PRISON,160
40880,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,113.0,KAMITI MAIN PRISON,653.0,4.929215e+13,KAMITI MAIN PRISON,653
40881,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,116.0,NAIROBI REMAND/ALLOCATION,90.0,4.929215e+13,NAIROBI REMAND/ALLOCATION,90
40882,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,118.0,KILGORIS PRISON,9.0,4.929215e+13,KILGORIS PRISON,9
40883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL REGISTERED VOTERS,19611423.0,NaN,NaN,19611423

In [4]:
#displaying information in the dataset 
df.info

<bound method DataFrame.info of        COUNTY CODE COUNTY NAME  CONSTITUENCY CODE CONSTITUENCY NAME  CAW CODE  \
0              1.0     MOMBASA                1.0         CHANGAMWE       1.0
1              1.0     MOMBASA                1.0         CHANGAMWE       1.0
2              1.0     MOMBASA                1.0         CHANGAMWE       1.0
3              1.0     MOMBASA                1.0         CHANGAMWE       1.0
4              1.0     MOMBASA                1.0         CHANGAMWE       1.0
...            ...         ...                ...               ...       ...
40879         49.0     PRISONS              292.0           PRISONS    1451.0
40880         49.0     PRISONS              292.0           PRISONS    1451.0
40881         49.0     PRISONS              292.0           PRISONS    1451.0
40882         49.0     PRISONS              292.0           PRISONS    1451.0
40883          NaN         NaN                NaN               NaN       NaN

         CAW_NAME  REGISTRATION CENTRE CODE     REGISTRATION CENTRE NAME  \
0      PORT REITZ                       1.0          BOMU PRIMARY SCHOOL
1      PORT REITZ                       1.0                          NaN
2      PORT REITZ                       1.0                          NaN
3      PORT REITZ                       1.0                          NaN
4      PORT REITZ                       1.0                          NaN
...           ...                       ...                          ...
40879     PRISONS                     112.0       KAMITI MEDIUM PRISON
40880     PRISONS                     113.0         KAMITI MAIN PRISON
40881     PRISONS                     116.0  NAIROBI REMAND/ALLOCATION
40882     PRISONS                     118.0            KILGORIS PRISON
40883         NaN                       NaN      TOTAL REGISTERED VOTERS

       VOTERS PER REGISTRATION CENTRE  POLLING STATION CODE  \
0                              9625.0          1.001000e+12
1                                 NaN          1.001000e+12
2                                 NaN          1.001000e+12
3                                 NaN          1.001000e+12
4                                 NaN          1.001000e+12
...                               ...                   ...
40879                           160.0          4.929215e+13
40880                           653.0          4.929215e+13
40881                            90.0          4.929215e+13
40882                             9.0          4.929215e+13
40883                      19611423.0                   NaN

            POLLING STATION NAME  VOTERS PER POLLING STATION
0            BOMU PRIMARY SCHOOL                         687
1            BOMU PRIMARY SCHOOL                         688
2            BOMU PRIMARY SCHOOL                         688
3            BOMU PRIMARY SCHOOL                         688
4            BOMU PRIMARY SCHOOL                         688
...                          ...                         ...
40879       KAMITI MEDIUM PRISON                         160
40880         KAMITI MAIN PRISON                         653
40881  NAIROBI REMAND/ALLOCATION                          90
40882            KILGORIS PRISON                           9
40883                        NaN                    19611423

[40884 rows x 12 columns]>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40884 entries, 0 to 40883
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   COUNTY CODE                     40883 non-null  float64
 1   COUNTY NAME                     40883 non-null  object
 2   CONSTITUENCY CODE               40883 non-null  float64
 3   CONSTITUENCY NAME               40883 non-null  object
 4   CAW CODE                        40883 non-null  float64
 5   CAW_NAME                        40883 non-null  object
 6   REGISTRATION CENTRE CODE        40883 non-null  float64
 7   REGISTRATION CENTRE NAME        24703 non-null  object
 8   VOTERS PER REGISTRATION CENTRE  24703 non-null  float64
 9   POLLING STATION CODE            40883 non-null  float64
 10  POLLING STATION NAME            40883 non-null  object
 11  VOTERS PER POLLING STATION      40884 non-null  int64
dtypes: float64(6), int64(1), object(5)
memory usage: 3.7+ MB

In [6]:
#Displaying table framework
df.shape

(40884, 12)

In [7]:
#Dropping one column
df.drop('CAW CODE',axis=1)

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
0,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,BOMU PRIMARY SCHOOL,9625.0,1.001000e+12,BOMU PRIMARY SCHOOL,687
1,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
2,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
3,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
4,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
...,...,...,...,...,...,...,...,...,...,...,...
40879,49.0,PRISONS,292.0,PRISONS,PRISONS,112.0,KAMITI MEDIUM PRISON,160.0,4.929215e+13,KAMITI MEDIUM PRISON,160
40880,49.0,PRISONS,292.0,PRISONS,PRISONS,113.0,KAMITI MAIN PRISON,653.0,4.929215e+13,KAMITI MAIN PRISON,653
40881,49.0,PRISONS,292.0,PRISONS,PRISONS,116.0,NAIROBI REMAND/ALLOCATION,90.0,4.929215e+13,NAIROBI REMAND/ALLOCATION,90
40882,49.0,PRISONS,292.0,PRISONS,PRISONS,118.0,KILGORIS PRISON,9.0,4.929215e+13,KILGORIS PRISON,9
40883,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL REGISTERED VOTERS,19611423.0,NaN,NaN,19611423

In [8]:
#Displaying dataset after dropping column
df

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW CODE,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
0,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,BOMU PRIMARY SCHOOL,9625.0,1.001000e+12,BOMU PRIMARY SCHOOL,687
1,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
2,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
3,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
4,1.0,MOMBASA,1.0,CHANGAMWE,1.0,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
...,...,...,...,...,...,...,...,...,...,...,...,...
40879,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,112.0,KAMITI MEDIUM PRISON,160.0,4.929215e+13,KAMITI MEDIUM PRISON,160
40880,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,113.0,KAMITI MAIN PRISON,653.0,4.929215e+13,KAMITI MAIN PRISON,653
40881,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,116.0,NAIROBI REMAND/ALLOCATION,90.0,4.929215e+13,NAIROBI REMAND/ALLOCATION,90
40882,49.0,PRISONS,292.0,PRISONS,1451.0,PRISONS,118.0,KILGORIS PRISON,9.0,4.929215e+13,KILGORIS PRISON,9
40883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL REGISTERED VOTERS,19611423.0,NaN,NaN,19611423

In [9]:
df = df.drop('CAW CODE',axis=1)

In [10]:
#Displaying rows in dataset
df.head()

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
0,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,BOMU PRIMARY SCHOOL,9625.0,1.001000e+12,BOMU PRIMARY SCHOOL,687
1,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
2,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
3,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
4,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688

In [11]:
#Displaying top 15 rows in the dataset
df.head(15)

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
0,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,BOMU PRIMARY SCHOOL,9625.0,1.001000e+12,BOMU PRIMARY SCHOOL,687
1,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
2,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
3,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
4,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
5,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
6,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
7,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,688
8,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
9,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
10,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
11,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
12,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
13,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,1.0,NaN,NaN,1.001000e+12,BOMU PRIMARY SCHOOL,687
14,1.0,MOMBASA,1.0,CHANGAMWE,PORT REITZ,2.0,MWIJABU PRIMARY SCHOOL,4468.0,1.001000e+12,MWIJABU PRIMARY SCHOOL,638

In [12]:
df.tail()

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
40879,49.0,PRISONS,292.0,PRISONS,PRISONS,112.0,KAMITI MEDIUM PRISON,160.0,4.929215e+13,KAMITI MEDIUM PRISON,160
40880,49.0,PRISONS,292.0,PRISONS,PRISONS,113.0,KAMITI MAIN PRISON,653.0,4.929215e+13,KAMITI MAIN PRISON,653
40881,49.0,PRISONS,292.0,PRISONS,PRISONS,116.0,NAIROBI REMAND/ALLOCATION,90.0,4.929215e+13,NAIROBI REMAND/ALLOCATION,90
40882,49.0,PRISONS,292.0,PRISONS,PRISONS,118.0,KILGORIS PRISON,9.0,4.929215e+13,KILGORIS PRISON,9
40883,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL REGISTERED VOTERS,19611423.0,NaN,NaN,19611423

In [13]:
#Displaying the last 10 rows in dataset
df.tail(10)

,COUNTY CODE,COUNTY NAME,CONSTITUENCY CODE,CONSTITUENCY NAME,CAW_NAME,REGISTRATION CENTRE CODE,REGISTRATION CENTRE NAME,VOTERS PER REGISTRATION CENTRE,POLLING STATION CODE,POLLING STATION NAME,VOTERS PER POLLING STATION
40874,49.0,PRISONS,292.0,PRISONS,PRISONS,105.0,KEHANCHA PRISON/KENDEGE,4.0,4.929215e+13,KEHANCHA PRISON/KENDEGE,4
40875,49.0,PRISONS,292.0,PRISONS,PRISONS,106.0,KISII MAIN,98.0,4.929215e+13,KISII MAIN,98
40876,49.0,PRISONS,292.0,PRISONS,PRISONS,107.0,KISII WOMEN,4.0,4.929215e+13,KISII WOMEN,4
40877,49.0,PRISONS,292.0,PRISONS,PRISONS,109.0,NAIROBI WEST,59.0,4.929215e+13,NAIROBI WEST,59
40878,49.0,PRISONS,292.0,PRISONS,PRISONS,110.0,LANGATA WOMEN PRISON,114.0,4.929215e+13,LANGATA WOMEN PRISON,114
40879,49.0,PRISONS,292.0,PRISONS,PRISONS,112.0,KAMITI MEDIUM PRISON,160.0,4.929215e+13,KAMITI MEDIUM PRISON,160
40880,49.0,PRISONS,292.0,PRISONS,PRISONS,113.0,KAMITI MAIN PRISON,653.0,4.929215e+13,KAMITI MAIN PRISON,653
40881,49.0,PRISONS,292.0,PRISONS,PRISONS,116.0,NAIROBI REMAND/ALLOCATION,90.0,4.929215e+13,NAIROBI REMAND/ALLOCATION,90
40882,49.0,PRISONS,292.0,PRISONS,PRISONS,118.0,KILGORIS PRISON,9.0,4.929215e+13,KILGORIS PRISON,9
40883,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL REGISTERED VOTERS,19611423.0,NaN,NaN,19611423

In [14]:
#Displaying two specific columns
df['REGISTRATION CENTRE CODE']

0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
         ...
40879    112.0
40880    113.0
40881    116.0
40882    118.0
40883      NaN
Name: REGISTRATION CENTRE CODE, Length: 40884, dtype: float64

In [15]:
#Displaying three specific columns
df[['COUNTY CODE', 'COUNTY NAME', 'CONSTITUENCY CODE']]

       COUNTY CODE COUNTY NAME  CONSTITUENCY CODE
0              1.0     MOMBASA                1.0
1              1.0     MOMBASA                1.0
2              1.0     MOMBASA                1.0
3              1.0     MOMBASA                1.0
4              1.0     MOMBASA                1.0
...            ...         ...                ...
40879         49.0     PRISONS              292.0
40880         49.0     PRISONS              292.0
40881         49.0     PRISONS              292.0
40882         49.0     PRISONS              292.0
40883          NaN         NaN                NaN

[40884 rows x 3 columns]